### ISSUE TITLE
Make Error

### ISSUE THREAD

**Issue by bibidfdf** [wonderfulzzd/TopADD_2D_3D_Arbitrary_TopOpt_in_PETSc#5]
Hello,

When I try to make the project by typing "make topopt", the system shows "No rule to make target `chkopts', needed by `topopt'.  Stop." Is there something wrong with the makefile?

**Comment by wonderfulzzd** [comment]
Hello bibidfdf,

Sorry for the delay.

You may be using a newer version of PETSc. When I am using 3.10.2, it is fine. When I switch to 3.16.3, there is a warning saying "Warning: chkopts target is deprecated and can be removed from user makefiles". So chkopts target has been deprecated in 3.16.3. Thus it may be removed if your PETSc version is even newer than 3.16.3.

In sum, I think you could go ahead to remove the "chkopts" in the makefile. Then it should be OK.

Thanks

Zhidong Brian Zhang
